### ISSUE TITLE
Dataset and metric discrepancy with original paper

### ISSUE THREAD

**Issue by Asichurter** [soarsmu/PatchNet#2]
Hello, I've downloaded data of PatchNet from Zenodo cause the url of Google Drive has become invalid. 
However, I found downloaded data may not be the original data in PatchNet paper when I was using it for further experiments. 

In original  PatchNet paper, this dataset has:
- 42,408 stable patches
- 39,995 non-stable patches
- 82,403 patches in total

and on balanced dataset PatchNet achieves:
- 0.860 AUC

---

But downloaded data has:
- 29161 stable patches
- 25319 non-stable patches
- 54480 patches in total

and on the downloaded data with downloaded model, PatchNet achieves:
- 0.9331 AUC

I'm wondering whether or not the given data is not the original data used in paper and this give rise to the discrepancy.
Many thanks for this.

**Comment by hvdthong** [comment]
Dear Asichurter, 

Many thanks for your question. It is the original data used in the paper. I remember that I had some requirements to clean the dataset. After this process, there are only (43,584 + 10,896) elements which satisfy the requirements. Moreover, there are some patches are used as the validation dataset which I didn't put here. 

Maybe I miss this information in the paper when I wrote the paper. 

Thank you and have a great week.

**Comment by Asichurter** [comment]
@hvdthong Got this, thanks for your quick reply for my question. Hope all goes well.
